Notas:

Pandas ocupa mucha memoría para trabajar(hay que elegir que es lo mejor usar)
Diferencia entre arrays y listas: arrays todos los elementos deben ser del mismo tipo, pesan menos de acuerdo a lo que se vaya a resolver  (Puntero de memoria en C--Buscar)
-Son de diferentes dimensiones: escalar, vector, matriz, tensor, tensor

Numpy: Nos permitirá trabjar con tensores de una forma mas eficiente

Slicing con Arrays: (Limpiar datos)

Operaciones con Arrays:

Todas las operaciones con matrices

También Numpy nos permite hacer operaciones estadisticas.

MASCARAS:

Obtener una matriz gemela pero de booleanos, se usa el modulo para el cometido




In [ ]:
pip install numpy

In [ ]:
import numpy as np

Q2.  Create a 1D array of numbers from 0 to 9

In [ ]:
b=np.arange(0,10)
b


Q3. Create a 3×3 numpy array of all True’s

In [ ]:
matriz=np.random.random((3,3))
mascara=((matriz%1!=0))
mascara

Q4. Extract all odd numbers from arr

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#> array([1, 3, 5, 7, 9])
arr[arr%2==1]

Q5. Replace all odd numbers in arr with -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr[arr%2==1]=-1
arr

Replace items that satisfy a condition without affecting the original array?

Q6. Replace all odd numbers in arr with -1 without changing arr

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out=np.where(arr%2==1,-1,arr) #Condicion, x, y -->  
                #Si se cumple, se devuelve el valor de x. Si no se cumple, el de y.
out

Reshape array

Q7. Convert a 1D array to a 2D array with 2 rows

In [ ]:
a=np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
a2=a[np.newaxis,5:]
print(a2)
a.reshape(2,5) # Setting to -1 automatically decides the number of cols


Stack two arrays vertically?

Q8. Stack arrays a and b vertically

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
np.concatenate([a,b],axis=0)
np.r_[a,b]

Stack two arrays horizontally?

Q9. Stack the arrays a and b horizontally.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.concatenate([a,b],axis=1)
np.c_[a, b]

Generate custom sequences in numpy without hardcoding?

Q10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a

In [ ]:
a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
np.r_[np.repeat(a, 2), np.tile(a,3)]

In [ ]:
np.intersect1d #Intercepta valores entre dos arrays
np.setdiff1d #Elimina todos los elementos que existen en otro array
np.where(a == b) #Nos permite obtener las posiciones donde los elementos se repiten
a[(a >= 5) & (a <= 10)] #Nos permite pbtener los elementos en ese rango del array


How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q15. Convert the function maxx that works on two scalars, to work on two arrays.

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [ ]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max=np.vectorize(maxx,otypes=[int]) #Vectorize para poder usar una funcion 
pair_max(a, b)

In [ ]:
arr = np.arange(9).reshape(3,3) #Itercambiando columnas 
print(arr)
a2=arr[:,[1,0,2]] 
print(a2)

In [ ]:
arr = np.arange(9).reshape(3,3) #Intercambiando filas 
print(arr)
a3=arr[[2,0,1],:]
print(a3)

In [111]:
#Q. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr[ : :-1] 


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
matriz=[[1,2,3],
        [4,5,6],
        [7,8,9]]
      #F  C
matriz[1][2]